services:
  - type: web
    name: vexa-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    staticPublishPath: .output/public
    healthCheckPath: /

  - type: web
    name: vexa-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5002

